version: "3"

services:

  redis:
    image: redis
    ports:
      - 6379:6379

  mongo-database:
    image: mongo
    ports:
      - 27017:27017

  postgres-database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=push-notification-service
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password

  airtable-service:
    build: ./airtable-service
    depends_on:
      - mongo-database
    volumes:
      - "./airtable-service:/opt/airtable-service"
      - "/opt/airtable-service/node_modules"
    ports:
      - 8000:8000
      - 9222:9222
    environment:
      - MONGO_URI=mongodb://mongo-database:27017/airtable-service
      - AIRTABLE_API_KEY
      - AIRTABLE_BASE_ID

  push-notification-service:
    build: ./push-notification-service
    depends_on:
      - postgres-database
    ports:
      - 9001:9000
      - 5006:5005
    volumes:
      - "./push-notification-service:/opt/push-notification-service"
      - "~/.sbt:/root/.sbt"
      - "~/.ivy2:/root/.ivy2"
      - "./certificates:/opt/certificates"
    environment:
      - SCALA_ENV=DEVELOPMENT
      - AIRTABLE_SERVICE_URL=http://airtable-service:8000
      - POSTGRES_URL=jdbc:postgresql://postgres-database:5432/push-notification-service
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - APNS_CERTIFICATE_PATH=/opt/certificates/flayrStylistAPNS.p12

  mobile-app-backend:
    build: ./mobile-app-backend
    depends_on:
      - airtable-service
      - push-notification-service
      - mongo-database
      - redis
    ports:
      - 9000:9000
      - 5005:5005
    volumes:
      - "./mobile-app-backend:/opt/mobile-app-backend"
      - "~/.sbt:/root/.sbt"
      - "~/.ivy2:/root/.ivy2"
      - "~/.aws:/root/.aws"
    environment:
      - SCALA_ENV=DEVELOPMENT
      - AIRTABLE_SERVICE_URL=http://airtable-service:8000
      - MONGO_URI=mongodb://mongo-database:27017/mobile-app-backend
      - PUSH_NOTIFICATION_SERVICE_URL=http://push-notification-service:9000
      - REDIS_HOST=redis
      - PASSCODE_LENGTH=2